### ISSUE TITLE
Index of Out of range error

### ISSUE THREAD

**Issue by ukamath** [sarnthil/unify-emotion-datasets#9]
After downloading and unifying the datasets, when I run the classify I get the following error

python3 classify_xvsy_logreg.py -d tec emoint
{'--all-vs': False,
 '--all-vs<': None,
 '--debug': True,
 '--force-multi': False,
 '--json': 'unified-dataset.jsonl',
 '--keep-last': False,
 '--output': '.',
 '<first>': 'tec',
 '<second>': 'emoint'}
Getting data
Detected mode: single...
0 0
Getting wordlist...
Getting emotions
Traceback (most recent call last):
  File "classify_xvsy_logreg.py", line 332, in <module>
    labels = get_labels(training_data, testing_data, mode=mode)
  File "classify_xvsy_logreg.py", line 69, in get_labels
    for emotion in test[0]["emotions"]
IndexError: list index out of range

**Comment by sarnthil** [comment]
Thanks for pointing this out. The issue is that EmoInt data is empty and couldn't be properly downloaded. I'll fix this ASAP.

Until then, either exclude EmoInt or download the dataset yourself from [Saif's website](http://saifmohammad.com/WebPages/SentimentEmotionLabeledData.html) and move it in the datasets folder. 

Also, if you don't find the data, drop me an email and I'll send it to you.

**Comment by ukamath** [comment]
Thanks. Can you send me as a zip at kamathuday at gmail.com, had issues putting it together. Thanks a lot
